### ISSUE TITLE
"Update available", app is on 0.2.4 but latest release is 0.2.5, no update available through docker

### ISSUE THREAD

**Issue by ShaneK** [ChuckMac/ADRFinder#11]
**Describe the bug**
My app is 0.2.4 but the latest release version is 0.2.5. Normally I'd use docker to update, but there's no update available.

**Version**
0.2.4

**To Reproduce**
- Install latest version through docker
- Notice it's 0.2.4 and the app says there's an update available

**Expected behavior**
The current version should match the latest release version on Github and there shouldn't be a new update available banner

**Screenshots**
![image](https://user-images.githubusercontent.com/561207/202501597-045d5477-6d7c-4da0-8fca-875f1663f8b7.png)
![image](https://user-images.githubusercontent.com/561207/202501714-1b724aee-1b84-4db1-93a1-e7116a2e6f39.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 106.0.5

**Smartphone (please complete the following information):**

**Additional context**
I know this is a minor issue, I'm just hoping you can update the docker repo so the banner on the app will go away when I update haha

Thanks for all of your hard work on this app!

**Comment by ChuckMac** [comment]
let me take a look... i think i messed up updating the version in the app first before i tagged it

**Comment by ShaneK** [comment]
Looks like your last deploy fixed the issue, excellent! Thank you!
