### ISSUE TITLE
Space 220 Restaurant 

### ISSUE THREAD

**Issue by viajb** [ChuckMac/ADRFinder#13]
I wanted to see if there were any errors with Space 220 Restaurant. I have gotten several alerts from other sites that reservations have been available from other services such as mouse dining and mouse watcher but each time they have showed availability, I have not gotten anything from the server. All the other restaurants have been working great. Unsure if their sites have false positives or they are just getting snagged before this checks.

**Comment by ChuckMac** [comment]
I haven't seen any specific issues with that... but unfortunately don't really have a way to test.    

You could try dropping your recheck time for it. I know the reservations go super quickly for it so might just be you never hit it at the right timing.
