### ISSUE TITLE
Initial Run Error

### ISSUE THREAD

**Issue by maygregio** [ChuckMac/ADRFinder#3]
**Describe the bug**
Error when launching the app for the first time (local Docker)

**To Reproduce**
1. Clone Docker
2. Run Docker
3. Open browser http://127.0.0.1:5500/

**From Docker Log**
172.17.0.1 - - [13/Apr/2022 12:05:45] "GET / HTTP/1.1" 500 450 25.340285
172.17.0.1 - - [13/Apr/2022 12:05:45] "GET /favicon.ico HTTP/1.1" 200 112296 0.006404
Creating JSON store at /datastore
(1) accepted ('172.17.0.1', 59600)
(1) accepted ('172.17.0.1', 59602)
ERROR:adrfinder:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/adrfinder/__init__.py", line 350, in index
    rest_and_times = get_restaurants_and_times()
  File "/app/adrfinder/__init__.py", line 1020, in get_restaurants_and_times
    search_times = rest.get_search_times()
  File "/app/adrfinder/restaurants.py", line 106, in get_search_times
    for option in search_data.find_all("option"):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by ChuckMac** [comment]
Thanks for the report.  Looks like that would indicate a (hopefully temporary) issue connecting to the Disney website.  Does it continue to fail if you bring it down and back up?

**Comment by ChuckMac** [comment]
closing stale issue

**Comment by ChuckMac** [comment]
Closing stale issue
