### ISSUE TITLE
Add Date/Time to "Last Checked" column

### ISSUE THREAD

**Issue by f1rstxlas7** [ChuckMac/ADRFinder#4]
First of all, this is incredible. This really is one of the most outstanding Disney Parks related repos I've seen thus far. Well done.

My only suggestion is to add the Date & Time in the "Last Checked" column. Reasoning being is that if I run things locally on my browser, I don't know exactly when that last run time was because something like "25 seconds ago" is arbitrary because there's no context to it.

Again, small suggestion, but great work here.

**Comment by ChuckMac** [comment]
I will start by saying - time is really hard in programming.  

This is cloned from the way Change Detection behaves and I don't really have any intention of updating it for now.
