### ISSUE TITLE
Access to container has stopped working.

### ISSUE THREAD

**Issue by gkeable** [ChuckMac/ADRFinder#7]
**Describe the bug**
Doesn't seem to work anymore for me, cannot connect via http://127.0.0.1:5500/
**Version**
In the top right area: 0.1.2

**To Reproduce**
Using desktop docker
docker pull chuckmacdev/adrfinder
docker run -d --restart always -p "127.0.0.1:5500:5500" -v datastore-volume:/datastore --name adrfinder chuckmacdev/adrfinder
http://127.0.0.1:5500/
results in

127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE

Docker logs shows

(1) wsgi starting up on http://0.0.0.0:5500
>> Request failed: 404 Client Error: Not Found for url: https://www.disneyworld.co.uk/dining/
(1) accepted ('172.17.0.1', 54274)
172.17.0.1 - - [05/Jul/2022 12:29:02] "GET / HTTP/1.1" 200 0 2.409906
wsgi exiting
(1) wsgi exited, is_accepting=True

**Additional context**
installed ping and curl within the container to test and could ping out to internet OK but curl to https://www.disneyworld.co.uk/dining/ resulted in refused connection.

**Comment by ChuckMac** [comment]
Disney has changed their auth schema for retrieving restaurants.  Working on updating it.

**Comment by gkeable** [comment]
Thanks, pesky Disney!

Cheers

Giles

**Comment by ChuckMac** [comment]
(and didn't mean to close this one)
